# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file" {
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the GCP Annotation MLOps stack recipe.
    zenml_version: ${var.zenml-version}
    stack_name: gcp_annotation_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        flavor: gcp
        name: gcs_artifact_store
        path: gs://${google_storage_bucket.artifact-store.name}
        authentication_secret: gcp_storage_secret
      container_registry:
        flavor: gcp
        name: gcr_container_registry
        uri: ${local.container_registry.region}.gcr.io/${local.project_id}
      metadata_store:
        flavor: sqlite
        name: REPLACEME
        upgrade_migration_enabled: true
        uri: ./metadata.db
      orchestrator:
        flavor: local
        name: local_orchestrator
      secrets_manager:
        flavor: gcp_secrets_manager
        name: gcp_secrets_manager
        project_id: ${local.project_id}
      annotator:
        authentication_secret: labelstudio_secret
        name: labelstudio_annotator
        port: 8093
    ADD
  filename = "./gcp_annotation_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yml"
}