# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file" {
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the GCP Kubeflow MLOps stack recipe.
    zenml_version: ${var.zenml-version}
    stack_name: gcp_kubeflow_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        id: ${uuid()}
        flavor: s3
        name: minio_artifact_store
        configuration: {
          "path": "s3://${minio_bucket.zenml_bucket.name}", 
          "key": "${var.zenml-minio-store-access-key}", 
          "secret": "${var.zenml-minio-store-secret-key}",
          "client_kwargs" : "{"endpoint_url":"${local.minio.host}:${local.minio.port}", "region_name":"us-east-1"}"
        }
      container_registry:
        id: ${uuid()}
        flavor: gcp
        name: local_container_registry
        configuration: {"uri": "${k3d_cluster.zenml-cluster.registries[0].create[0].host}:${k3d_cluster.zenml-cluster.registries[0].create[0].host_port}"}
      orchestrator:
        id: ${uuid()}
        flavor: kubeflow
        name: k3d_kubeflow_orchestrator
        configuration: {"kubernetes_context": "k3d-${k3d_cluster.zenml-cluster.name}", "synchronous": True}
    ADD
  filename = "./k3d_kubeflow_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yaml"
}