# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file" {
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the K3D Kubeflow MLOps stack recipe.
    zenml_version: ${var.zenml-version}
    stack_name: k3d_minimal_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        id: ${uuid()}
        flavor: s3
        name: minio_artifact_store
        configuration: {
          "path": "s3://${minio_bucket.zenml_bucket.name}", 
          "key": "${var.zenml-minio-store-access-key}", 
          "secret": "${var.zenml-minio-store-secret-key}",
          "client_kwargs" : '{"endpoint_url":"http://${docker_container.minio_server.network_data[0].ip_address}:${local.minio.port}", "region_name":"us-east-1"}'
        }
      container_registry:
        id: ${uuid()}
        flavor: default
        name: k3d-${local.k3d_registry.name}-${random_string.cluster_id.result}
        configuration: {"uri": "${local.k3d_registry.host}:${local.k3d_registry.port}"}
      orchestrator:
        id: ${uuid()}
        flavor: kubeflow
        name: k3d_kubeflow_orchestrator
        configuration: {"kubernetes_context": "k3d-${k3d_cluster.zenml-cluster.name}", "synchronous": True, "skip_local_validations" : True}
    ADD
  filename = "./k3d_kubeflow_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yaml"
}