# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file" {
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the GCP Minimal MLOps stack recipe.
    zenml_version: ${var.zenml-version}
    stack_name: gcp_minimal_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        id: ${uuid()}
        flavor: gcp
        name: gcs_artifact_store
        configuration: {"path": "gs://${google_storage_bucket.artifact-store.name}"}
      container_registry:
        id: ${uuid()}
        flavor: gcp
        name: gcr_container_registry
        configuration: {"uri": "${local.container_registry.region}.gcr.io/${local.project_id}"}
      orchestrator:
        id: ${uuid()}
        flavor: airflow
        name: gcp_composer_airflow
        configuration: {}
      secrets_manager:
        id: ${uuid()}
        flavor: gcp
        name: gcp_secrets_manager
        configuration: {"project_id": "${local.project_id}"}
    ADD
  filename = "./gcp_minimal_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yaml"
}