# DEPRECATION WARNING: This code has been deprecated
# The maintained & current code can be found at src/mlstacks/terraform/
# under the same relative location.

# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file" {
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the AzureML Minimal MLOps stack recipe.
    zenml_version: ${var.zenml-version}
    stack_name: azureml_minimal_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      orchestrator:
        id: ${uuid()}
        flavor: local
        name: default
        configuration: {}
      artifact_store:
        id: ${uuid()}
        flavor: azure
        name: azureml_artifact_store
        configuration: {"path": "az://${azurerm_storage_container.artifact-store.name}", "authentication_secret": "azureml-storage-secret"}
      step_operator:
        id: ${uuid()}
        flavor: azureml
        name: azureml_step_operator
        configuration: {"subscription_id": "${data.azurerm_client_config.current.subscription_id}", "resource_group": "${azurerm_resource_group.rg.name}", "workspace_name": "${azurerm_machine_learning_workspace.mlw.name}", "compute_target_name": "${azurerm_machine_learning_compute_cluster.cluster.name}"}
      secrets_manager:
        id: ${uuid()}
        flavor: azure
        name: azureml_secrets_manager
        configuration: {"key_vault_name": "${azurerm_key_vault.secret_manager.name}"}
      experiment_tracker:
        id: ${uuid()}
        flavor: mlflow
        name: azureml_mlflow_experiment_tracker
        configuration: {"tracking_uri": "https://${azurerm_resource_group.rg.location}.api.azureml.ms/mlflow/v1.0/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${azurerm_resource_group.rg.name}/providers/Microsoft.MachineLearningServices/workspaces/${local.prefix}-${local.azureml.cluster_name}-mlw", "tracking_token": "REPLACE_ME"}
    ADD
  filename = "./azureml_minimal_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yaml"
}
