# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file_mlflow" {
  count    = local.enable_mlflow ? 1 : 0
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the Vertex AI stack recipe.

    zenml_version: ${var.zenml-version}
    stack_name: vertex_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        flavor: gcp
        name: gcs_artifact_store
        path: gs://${google_storage_bucket.artifact-store.name}
      container_registry:
        flavor: gcp
        name: gcr_container_registry
        uri: ${local.container_registry.region}.gcr.io/${local.project_id}
      metadata_store:
        database: zenml_db
        flavor: mysql
        host: ${module.metadata_store.instance_first_ip_address}
        name: cloudsql_metadata_store
        port: 3306
        secret: mysql_secret
        upgrade_migration_enabled: true
      orchestrator:
        flavor: vertex
        labels: {}
        location: ${local.vertex_ai.region}
        name: vertex_ai_orchestrator
        project: ${local.project_id}
        synchronous: false
        workload_service_account: ${google_service_account.sa.email}
      secrets_manager:
        flavor: gcp_secrets_manager
        name: gcp_secrets_manager
        project_id: ${local.project_id}
      experiment_tracker:
        flavor: mlflow
        name: gke_mlflow_experiment_tracker
        tracking_uri: http://${data.kubernetes_service.mlflow_tracking[0].status.0.load_balancer.0.ingress.0.ip}
        tracking_username: ${var.mlflow-username}
        tracking_password: ${var.mlflow-password}
    ADD
  filename = "./vertex_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yml"
}

resource "local_file" "stack_file" {
  count    = local.enable_mlflow ? 0 : 1
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the Vertex AI stack recipe.

    zenml_version: ${var.zenml-version}
    stack_name: vertex_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        flavor: gcp
        name: gcs_artifact_store
        path: gs://${google_storage_bucket.artifact-store.name}
      container_registry:
        flavor: gcp
        name: gcr_container_registry
        uri: ${local.container_registry.region}.gcr.io/${local.project_id}
      metadata_store:
        database: zenml_db
        flavor: mysql
        host: ${module.metadata_store.instance_first_ip_address}
        name: cloudsql_metadata_store
        port: 3306
        secret: mysql_secret
        upgrade_migration_enabled: true
      orchestrator:
        flavor: vertex
        labels: {}
        location: ${local.vertex_ai.region}
        name: vertex_ai_orchestrator
        project: ${local.project_id}
        synchronous: false
        workload_service_account: ${google_service_account.sa.email}
      secrets_manager:
        flavor: gcp_secrets_manager
        name: gcp_secrets_manager
        project_id: ${local.project_id}
    ADD
  filename = "./vertex_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yml"
}