# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file_mlflow" {
  count    = local.enable_mlflow ? 1 : 0
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the Vertex AI stack recipe.

    zenml_version: ${var.zenml-version}
    stack_name: vertex_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        flavor: gcp
        name: gcs_artifact_store
        configuration: {"path": "gs://${google_storage_bucket.artifact-store.name}"}
      container_registry:
        flavor: gcp
        name: gcr_container_registry
        configuration: {"uri": "${local.container_registry.region}.gcr.io/${local.project_id}"}
      orchestrator:
        flavor: vertex
        name: vertex_ai_orchestrator
        configuration: {"workload_service_account": "${google_service_account.sa.email}", "project": "${local.project_id}", "location": "${local.vertex_ai.region}", "labels": "{}"}
      secrets_manager:
        flavor: gcp_secrets_manager
        name: gcp_secrets_manager
        configuration: {"project_id": "${local.project_id}"}
      experiment_tracker:
        flavor: mlflow
        name: gke_mlflow_experiment_tracker
        configuration: {"tracking_uri": "http://${data.kubernetes_service.mlflow_tracking[0].status.0.load_balancer.0.ingress.0.ip}", "tracking_username": "${var.mlflow-username}", "tracking_password": "${var.mlflow-password}"}
    ADD
  filename = "./vertex_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yml"
}

resource "local_file" "stack_file" {
  count    = local.enable_mlflow ? 0 : 1
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the Vertex AI stack recipe.

    zenml_version: ${var.zenml-version}
    stack_name: vertex_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        flavor: gcp
        name: gcs_artifact_store
        configuration: {"path": "gs://${google_storage_bucket.artifact-store.name}"}
      container_registry:
        flavor: gcp
        name: gcr_container_registry
        configuration: {"uri": "${local.container_registry.region}.gcr.io/${local.project_id}"}
      orchestrator:
        flavor: vertex
        name: vertex_ai_orchestrator
        configuration: {"workload_service_account": "${google_service_account.sa.email}", "project": "${local.project_id}", "location": "${local.vertex_ai.region}", "labels": "{}"}
      secrets_manager:
        flavor: gcp_secrets_manager
        name: gcp_secrets_manager
        configuration: {"project_id": "${local.project_id}"}
    ADD
  filename = "./vertex_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yml"
}