name: Publish PyPi package

on:
  workflow_call:

jobs:
  publish_to_pypi:
    name: Publish Python 🐍 package 📦 to PyPI
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: "utf-8"

    steps:
      - uses: actions/checkout@v3

      - name: Get the version from the github tag ref
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          if [ "$(cat src/mlstacks/VERSION)" = "$(echo ${GITHUB_REF} | sed 's|refs/tags/||g')" ];
          then ./scripts/publish.sh;
          else echo "Version mismatch between src/zenml/VERSION and branch tag" && exit 1;
          fi
